### ISSUE TITLE
RouteMatcher#giveMatch

### ISSUE THREAD

**Issue by smallclover** [biezhi/jb#10]
打扰您，很抱歉。
对于Collections.sort方法中的判断条件不是很理解。判断相同之后，返回uri所在的索引位置。但是既然相同了，索引位置一定是0不是么？希望能详细解释一下。谢谢

**Comment by hellokaton** [comment]
之前这种方法是比较笨的，如果你对路由感兴趣你可以看看 [这篇](http://www.scienjus.com/fastroute-spring/) 文章，还有一个我最近关注的库：https://github.com/noahbuscher/Macaw
