### ISSUE TITLE
注解的值和class比较不是很懂

### ISSUE THREAD

**Issue by honwhy** [biezhi/jb#3]
jb/cache/3.myioc.md

```
if(autoWrited.value() == Class.class){
    autoWritedField = recursiveAssembly(field.getType());
} 
```

这块代码不是很懂。
请教一下。

**Comment by hellokaton** [comment]
这里使用AutoWrited注解作为注入的注解，在这个注解上有2个属性，一个是value，另一个是name。
这块代码判断value的class类型的什么，然后去获取一个符合value的对象，最终注入进去，你可以打断点试试。
