### ISSUE TITLE
MVC学习

### ISSUE THREAD

**Issue by gdjdsjh** [biezhi/jb#8]
貌似MVC那块的源码和讲解没对应起来，不太好学习，希望作者能更新一下^-^

**Comment by hellokaton** [comment]
可以具体指出一下吗，过了很长时间可能记不清了。

**Comment by gdjdsjh** [comment]
比如源码里的Bootstrap类、wrapper包下里面的Request和Response类，util包下面的ExceptionUtil和ReflectUtil类好像都没提及。我跟着你写的时候发现Eclipse提示没有该类，我以为你后面会讲，结果发现没有，看了你的源码才发现多了好几个类，估计是你后来更新的吧^-^

**Comment by hellokaton** [comment]
这样啊，文章里不会提及工具类的东西的，只是大致讲思路和方法，具体实现可以直接参考源码的。
Bootstrap这些类都是后来加上去的，我修改一下文档。

**Comment by gdjdsjh** [comment]
恩，可以在前面说明一下，这样就不会困惑了。BTW，什么时候写ORM框架实现篇啊？^-^

**Comment by hellokaton** [comment]
最近在忙论坛，等稳定下来。

**Comment by gdjdsjh** [comment]
好厉害！膜拜一下！
